AllCops:
  NewCops: enable

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/MethodLength:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 9

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/rooms_controller.rb'
    - 'app/controllers/schedules_controller.rb'
    - 'app/models/application_record.rb'
    - 'app/models/room.rb'
    - 'app/models/schedule.rb'
    - 'config/application.rb'
    - 'db/migrate/20220119205321_create_rooms.rb'
    - 'db/migrate/20220119212558_create_schedules.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'bin/bundle'
